packages:
  - 'example/**'
  - 'moose-drag/**'
  - 'moose-dynamic/**'
  - 'moose-emitter/**'
  - 'moose-form/**'
  - 'moose-table/**'
  - 'moose-cond-table/**'
  - 'moose-utils/**'
  - 'moose-theme/**'
  - 'moose-directive/**'
  - 'moose-svg-editor/**'
  - 'moose-video-client/**'
  - 'moose-xlsx/**'
